#配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.3.20:3306/promise-message?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  # Rabbit MQ
  rabbitmq:
    host: 192.168.3.88
    port: 5672
    username: ares5k
    password: ares5k
    virtual-host: promise-message-virtual
    publisher-confirm-type: correlated
    publisher-returns: true

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: id_worker_str
  configuration:
    map-underscore-to-camel-case: true